# Generated by Django 6.0.3 on 2026-03-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_origem', models.CharField(max_length=3)),
                ('moeda_destino', models.CharField(max_length=3)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_convertido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_conversao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
